select CONTAINER_ID, CONTAINER_STATUS_CD, CONTAINER_VALIDATED_FLAG, CONTAINER_VALIDATED_DT, DESTINATION_SORT_GROUP_SEQ,
       HUB_LOCATION_SEQ, PROCESSING_CTG, TRIP_STOP_SEQ, CONTAINER_TYPE_CD, CHUTE_LOC_SEQ, CHUTE_NM, BOL_PACKAGE_CNT,
       BOL_PACKAGE_WGT, CARRIER_SMS_CNTC_SEQ, TMS_LOAD_SEQ_ID
from CONTAINER sample(1) where rownum < 2
